### ISSUE TITLE
creation of permutation set

### ISSUE THREAD

**Issue by robeach78** [ComputationalSystemsBiology/ExoProfiler#10]
the server to create the permutated sequences is down or something

**Comment by rsa-tools** [comment]
Thank you for notifying us. Is it still inaccessible ?

**Comment by robeach78** [comment]
no now it works!

thanks

On Nov 16, 2018, at 2:41 PM, rsa-tools <notifications@github.com<mailto:notifications@github.com>> wrote:

Thank you for notifying us. Is it still inaccessible ?

**Comment by ibn-salem** [comment]
Ok, thank you. I close this issue.
