### ISSUE TITLE
normalized coverage

### ISSUE THREAD

**Issue by robeach78** [ComputationalSystemsBiology/ExoProfiler#3]
In your pubblications and figures it refers to normalized ChIP-exo coverage, 
but then after using the bam file provided by my experiments I don't see a normalized count.

how do you get that? Is is extracted from the bam file with the genomeCoverageBed function?

thanks,
R

**Comment by ibn-salem** [comment]
Some plots show read counts that are normalized by the number of binding sites. This is calculated in the 02_exoPlotter/exoPlotter.R script. 
Hope this helps.
